spring:
  thymeleaf:
    suffix: .html
    cache: false
    enabled: true
  application:
    name: test-security-spring
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/test10102024
    username: postgres
    password: root123
server:
  port: 8080

